name: dental-xray
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pip
  - pip:
    - ultralytics==8.2.0
    - gradio==5.0.0
    - opencv-python==4.10.0.84
    - pillow==10.4.0
    - numpy==2.0.2
    - pandas==2.2.3
    - matplotlib==3.9.2
    - seaborn==0.13.2
    - scikit-learn>=1.3.0
    - tabulate>=0.9.0
    - jupyter==1.1.1
    - ipykernel==6.29.5
    - roboflow==1.1.40
    - thop==0.1.1-2209072238
